# 1. 特征值、特征向量求解
    下图为对矩阵求特征值、求特征向量的相关操作。

![](Learn_Pictures/02-线性代数/img.png)

# 2. 标量运算

![](Learn_Pictures/02-线性代数/img_1.png)

# 3. 向量运算
    下图中，α是一个标量，
    是把向量b拉长。

![](Learn_Pictures/02-线性代数/img_2.png)

![](Learn_Pictures/02-线性代数/img_3.png)

![](Learn_Pictures/02-线性代数/img_4.png)

# 4. 矩阵运算

![](Learn_Pictures/02-线性代数/img_5.png)

![](Learn_Pictures/02-线性代数/img_6.png)

![](Learn_Pictures/02-线性代数/img_7.png)

![](Learn_Pictures/02-线性代数/img_8.png)

    矩阵长度叫范数，下图为矩阵范数满足的公式。

![](Learn_Pictures/02-线性代数/img_9.png)

![](Learn_Pictures/02-线性代数/img_10.png)

![](Learn_Pictures/02-线性代数/img_11.png)

# 5. 特征向量、特征值
    红色、绿色向量都被一个矩阵作用后，红色的大小和方向都被改变了，绿色的仅被改变了大小，没有改变方向。绿色向量为矩阵的特征向量。

![](Learn_Pictures/02-线性代数/img_12.png)

# 6. 线性代数
## 6.1 标量
    标量由只有一个元素的张量表示。

In [81]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

## 6.2 向量
### 6.2.1 创建向量
    可以将向量视为标量值组成的列表。

In [82]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

### 6.2.2 访问向量元素
    通过张量的索引来访问任一元素。

In [83]:
import torch
x = torch.arange(4)
print(x[3])  # 索引从0开始

tensor(3)


### 6.2.3 访问向量长度
    访问张量的长度。

In [84]:
import torch
x = torch.arange(4)
len(x)

4

### 6.2.4 访问向量维度
    只有一个轴的张量，形状只有一个元素。

In [85]:
import torch
x = torch.arange(4)
x.shape

torch.Size([4])

## 6.3 矩阵
### 6.3.1 创建矩阵
    通过指定两个分量m和n来创建一个形状为m×n的矩阵。

In [86]:
import torch
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

### 6.3.2 矩阵转置
    矩阵的转置。

In [87]:
A = torch.arange(20).reshape(5, 4)
A.T # 矩阵的转置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

### 6.3.3 对称矩阵
对称矩阵（symmetric matrix）A 等于其转置：$A = A^{T}$

In [88]:
B = torch.tensor([[1, 2, 3], [2, 0, 4],[3 ,4 ,5]])
print(B)
print(B == B.T)

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### 6.3.4 多维矩阵
    就像向量是标量的推广，矩阵是向量的推广一样，可以构建更多轴的数据结构。

In [89]:
import torch
X = torch.arange(24).reshape(2, 3, 4)
print(X)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


### 6.3.5 矩阵克隆
    给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量。

In [90]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 通过分配新内存，将A的一个副本分配给B
print(A)
print(A + B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])


### 6.3.6 矩阵相乘（对应元素相乘）
    两个句子的按元素乘法称为哈达玛积（Hadamard product）（数学符号⊙）

In [91]:
import torch
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone() # 通过分配新内存，将A的一个副本分配给B
print(A)
print(A * B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


### 6.3.7 矩阵加标量

In [92]:
a = 2
X =  torch.arange(24).reshape(2, 3, 4)
print(a + X)
print((a * X).shape)

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])
torch.Size([2, 3, 4])


## 6.3.8 向量求和
    计算所有元素的和。

In [93]:
x = torch.arange(4,dtype=torch.float32)
print(x)
print(x.sum())

tensor([0., 1., 2., 3.])
tensor(6.)


### 6.3.9 矩阵求和
    表示任意形状张量的元素和。

In [94]:
import torch
A = torch.arange(20*2).reshape(2,5,4)
print(A.shape)
print(A.sum())

torch.Size([2, 5, 4])
tensor(780)


### 6.3.10 矩阵某轴求和（维度丢失）
    指定张量沿哪一个轴来通过求和降低维度。
    axis = 0垂直求和，axis = 1纵向求和，axis = 2横向求和

In [95]:
import torch
A = torch.arange(20*2).reshape(2,5,4)
print(A)
A_sum_axis0 = A.sum(axis = 0) # (2,5,4) 对第一个维度进行求和，剩下两个维度留下来了
print(A_sum_axis0)
print(A_sum_axis0.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])
tensor([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])
torch.Size([5, 4])


In [96]:
import torch
A = torch.arange(20*2).reshape(2,5,4)
print(A)
A_sum_axis1 = A.sum(axis=1) # (2,5,4) 对第二个维度进行求和，剩下两个维度留下来了
print(A_sum_axis1)
print(A_sum_axis1.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])
tensor([[ 40,  45,  50,  55],
        [140, 145, 150, 155]])
torch.Size([2, 4])


In [97]:
import torch
A = torch.arange(20*2).reshape(2,5,4)
print(A)
A_sum_axis1 = A.sum([0,1]) # (2,5,4) 对第一、二个维度进行求和，剩下一个维度留下来了
print(A_sum_axis1)
print(A_sum_axis1.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])
tensor([180, 190, 200, 210])
torch.Size([4])


### 6.3.11 矩阵平均值
    一个与求和相关的量是平均值（mean或average）。

In [98]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
print(A.mean())
print(A.sum()/A.numel()) # numel()是A的个数

tensor(9.5000)
tensor(9.5000)


In [1]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
print(A)
print(A.mean(axis = 0))
print(A.sum(axis=0))
print(A.shape[0])
print(A.sum(axis = 0)/A.shape[0])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([ 8.,  9., 10., 11.])
tensor([40., 45., 50., 55.])
5
tensor([ 8.,  9., 10., 11.])


### 6.3.12 矩阵某轴求和（维度不丢失）
    计算总和或均值时保持轴数不变。

In [100]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
sum_A = A.sum(axis = 1, keepdims = True) # keepdims=True不丢掉维度，否则三维矩阵按一个维度求和就会变为二维矩阵，二维矩阵若按一个维度求和就会变为一维向量
print(A)
print(sum_A)
print(sum_A.shape) # 维度没有丢失，方便使用广播

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
torch.Size([5, 1])


### 6.3.13 矩阵广播
    通过广播将 A 除以 sum_A。

In [101]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
sum_A = A.sum(axis=1,keepdims=True) # keepdims=True不丢掉维度，否则三维矩阵按一个维度求和就会变为二维矩阵，二维矩阵若按一个维度求和就会变为一维向量
print(A/sum_A)

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])


### 6.3.14 矩阵某轴累加
    某个轴计算A元素的累加总和。

In [102]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
print(A)
print(A.cumsum(axis = 0)) # 按列向下累加

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


### 6.3.15 向量点积
    点积是相同位置的按元素成绩的和。

In [103]:
import torch
x = torch.arange(4,dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
print(x)
print(y)
print(torch.dot(x, y)) # 0*1 + 1*1 + 2*1 + 3*1 = 6

tensor([0., 1., 2., 3.])
tensor([1., 1., 1., 1.])
tensor(6.)


    可以通过执行按元素乘法，然后进行求和来表示两个向量的点积。

In [104]:
import torch
x = torch.arange(4,dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)
print(torch.sum(x*y))

tensor(6.)


### 6.3.16 矩阵向量积
A是一个m×n的矩阵，x是一个n×1的矩阵，矩阵向量积$Ax$是一个长度为m的列向量，其第i个元素是点积$a^{⊤}_{i}x$。

In [105]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
x = torch.arange(4,dtype=torch.float32)
print(A)
print(x)
print(A.shape)
print(x.shape)
print(torch.mv(A, x))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([0., 1., 2., 3.])
torch.Size([5, 4])
torch.Size([4])
tensor([ 14.,  38.,  62.,  86., 110.])


### 6.3.17 矩阵相乘（线性代数相乘）
    可以将矩阵-矩阵乘法AB看作是简单地执行m次矩阵-向量积，并将结果拼接在一起，形成一个n×m矩阵。

In [106]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = torch.ones(4,3)
print(A)
print(B)
torch.mm(A, B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

### 6.3.18 矩阵L2范数
L2 范数是向量元素平方和的平方根：
$\|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^n x_i^2}$

In [107]:
import torch
u = torch.tensor([3.0, -4.0])
print(u)
print(torch.norm(u)) # 3**3 + -4**-4 开根号 = 5

tensor([ 3., -4.])
tensor(5.)


### 6.3.19 矩阵L1范数
$L_{1}$范数，它表示为向量元素的绝对值之和：$\|\mathbf{x}\|_1 = \sum_{i=1}^n \left|x_i \right|$

In [108]:
import torch
u = torch.tensor([3.0,-4.0])
torch.abs(u).sum() # 3 + 4 = 7

tensor(7.)

### 6.3.20 矩阵F范数
矩阵的弗罗贝尼乌斯范数（Frobenius norm）是矩阵元素的平方和的平方根：$$\|\mathbf{X}\|_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}$$

In [109]:
import torch
A = torch.ones((4,9))
print(A)
print(torch.norm(A)) # 把矩阵拉成一个向量，然后再求和    4 * 9 = 36 再开平方

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor(6.)
