# 1. N维数组
    N维数组是机器学习和神经网络的主要数据结构
    0-d(标量)     1-d(向量)         2-d(矩阵)         3-d(图片)
      1.0      [1.0,2.7,3.4]    [[1.0,2.7,3.4]     (宽*高*通道)
                                [1.0,2.7,3.4]
                                [1.0,2.7,3.4]]
    ----------------------------------------------------------
            4-d                     5-d
    (批量大小*宽*高*通道)     (批量大小*时间*宽*高*通道)

# 2. 创建数组
    创建数组需要：形状、数据类型、元素值。
    形状：例如3×4矩阵
    每个元素的数据类型：例如32位浮点数
    每个元素的值，例如全是0，或者随机数

# 3. 访问元素
    可以根据切片，或者间隔步长访问元素。
    [::3,::2]是每隔3行、2列访问。

# 4. 张量数据操作
## 4.1 导入torch库
    虽然库为PyTorch库，但应该导入torch，而不是pytorch

In [1]:
import torch
x = torch.arange(12) # 初始化一个0-11的张量，张量表示一个数值组成的数组，这个数组可能有多个维度
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 4.2 访问张量形状
    可以通过张量的shape属性来访问张量的形状和张量中元素的总数。

In [2]:
import torch
x = torch.arange(12) # 初始化一个0-11的张量
x.shape # 张量的形状

torch.Size([12])

In [3]:
import torch
x = torch.arange(12) # 初始化一个0-11的张量
x.numel() # 张量中元素的总数

12

## 4.3 改变张量形状
    要改变一个张量的形状而不改变元素数量和元素值，可以调用reshape函数。

In [4]:
import torch
x = torch.arange(12) # 初始化一个0-11的张量
x = x.reshape(3,4) # 一维张量改为3行四列的张量
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

## 4.4 创建全0、全1张量
    使用全0、全1、其他常量或者从特定分布中随即采样的数字

In [5]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

## 4.5 创建特定值张量
    通过提供包含数值的Python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值。

In [7]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])# 二维tensor

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [8]:
torch.tensor([[[2,1,4,3],[1,2,3,4],[4,3,2,1]]]) # 三维tensor

tensor([[[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]])

In [9]:
import torch
y = torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]]) # 二维tensor
z = torch.tensor([[[2,1,4,3],[1,2,3,4],[4,3,2,1]]]) # 三维tensor
print(y.shape)
print(z.shape)

torch.Size([3, 4])
torch.Size([1, 3, 4])


## 4.6 张量运算操作
    常见的标准算术运算符(+、-、*、/、和 **)都可以被升级为按元素运算。

In [10]:
import torch
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)# **运算符是求幂运算

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])


    对每个元素应用更多的计算。

In [12]:
import torch
x = torch.tensor([1.0,2,4,8])
x = torch.exp(x) # e的x次方
print(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


## 4.7 张量合并操作
    可以把多个张量结合在一起

In [13]:
import torch
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
m = torch.cat([x,y],dim=0) # 按行合并起来
n = torch.cat([x,y],dim=1) # 按列合并起来
print(m)
print(n)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


## 4.8 张量逻辑运算
    通过逻辑运算符构建二元张量。

In [14]:
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
print(x)
print(y)
print(x == y)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


## 4.9 张量累加运算
    对张量中所有元素进行求和会产生一个只有一个元素的张量。

In [15]:
import torch
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
x.sum()

tensor(66.)

## 4.10 张量广播运算
    即使形状不同，仍然可以通过调用广播机制(broadcasting mechanism) 来执行按元素操作。

In [16]:
import torch
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print(a)
print(b)
print(a+b) # a会复制出一个3*2的矩阵，b复制出一个3*2的矩阵，然后再相加，会得到一个3*2矩阵

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


## 4.11 张量访问运算
    可以用[-1]选择最后一个元素，可以用[1:3]选择第二个和第三个元素。

In [17]:
import torch
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
print(x[-1])
print(x[1:3])

tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


## 4.12 张量元素改写
    除读取外，还可以通过指定索引来将元素写入矩阵。

In [18]:
import torch
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
x[1,2] = 9
print(x)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])


    为多个元素赋值相同的值，只需要索引所有元素，然后为它们赋值。

In [19]:
x[0:2,:] = 12
print(x)

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


## 4.13 张量内存变化
    运行一些操作可能会导致为新结果分配内容。

In [20]:
import torch
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
before = id(y) # 和c++中指针类似
y = y + x
id(y) == before  # 运行操作后，赋值后的y的id和原来的id不一样

False

In [21]:
z = torch.zeros_like(y) # z 的数据类型、尺寸和y一样，里面的元素全为0
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 2742197051040
id(z): 2742197051040


    如果在后续计算中没有重复使用X，即内存不会过多复制，也可以使用X[:] = X + Y 或 X += Y 来减少操作的
    内存开销。

In [22]:
before = id(x)
x += y
print(id(x) == before)

True


## 4.14 张量转Numpy
    张量转 NumPy。

In [23]:
import torch
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
a = x.numpy()
b = torch.tensor(a)
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


    将大小为1的张量转为 Python 标量。

In [28]:
a = torch.tensor([3.5])
print(a)
print(a.item())
print(float(a))
print(int(a))

tensor([3.5000])
3.5
3.5
3


# 5. 数据预处理
## 5.1 创建数据集
    创建一个人工数据集，并存储在csv(逗号分隔符)文件。