# 1. 特征值、特征向量求解
    下图为对矩阵求特征值、求特征向量的相关操作。

![](Learn_Pictures/02-线性代数/img.png)

# 2. 标量运算

![](Learn_Pictures/02-线性代数/img_1.png)

# 3. 向量运算
    下图中，α是一个标量，
    是把向量b拉长。

![](Learn_Pictures/02-线性代数/img_2.png)

![](Learn_Pictures/02-线性代数/img_3.png)

![](Learn_Pictures/02-线性代数/img_4.png)

# 4. 矩阵运算

![](Learn_Pictures/02-线性代数/img_5.png)

![](Learn_Pictures/02-线性代数/img_6.png)

![](Learn_Pictures/02-线性代数/img_7.png)

![](Learn_Pictures/02-线性代数/img_8.png)

    矩阵长度叫范数，下图为矩阵范数满足的公式。

![](Learn_Pictures/02-线性代数/img_9.png)

![](Learn_Pictures/02-线性代数/img_10.png)

![](Learn_Pictures/02-线性代数/img_11.png)

# 5. 特征向量、特征值
    红色、绿色向量都被一个矩阵作用后，红色的大小和方向都被改变了，绿色的仅被改变了大小，没有改变方向。绿色向量为矩阵的特征向量。

![](Learn_Pictures/02-线性代数/img_12.png)

# 6. 线性代数
## 6.1 标量
    标量由只有一个元素的张量表示。

In [1]:
import torch
from d2l.tensorflow import reshape

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

## 6.2 向量
### 6.2.1 创建向量
    可以将向量视为标量值组成的列表。

In [3]:
x = torch.arange(4)
x

(tensor([0, 1, 2, 3]), tensor(3))

### 6.2.2 访问向量元素
    通过张量的索引来访问任一元素。

In [5]:
import torch
x = torch.arange(4)
print(x[3])  # 索引从0开始

tensor(3)


### 6.2.3 访问向量长度
    访问张量的长度。

In [6]:
import torch
x = torch.arange(4)
len(x)

4

### 6.2.4 访问向量维度
    只有一个轴的张量，形状只有一个元素。

In [7]:
import torch
x = torch.arange(4)
x.shape

torch.Size([4])

## 6.3 矩阵
### 6.3.1 创建矩阵
    通过指定两个分量m和n来创建一个形状为m×n的矩阵。

In [10]:
import torch
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

### 6.3.2 矩阵转置
    矩阵的转置。

In [12]:
A = torch.arange(20).reshape(5, 4)
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

### 6.3.3 对称矩阵
对称矩阵（symmetric matrix）A 等于其转置：$A = A^{T}$